# Copyright 2018 Creu Blanca
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
{
    "name": "Banas-Account Loan management",
    "version": "11.0.1.2.0",
    "icon":"/static/description/odoo_icon.png",
    "author": "BanasTech",
    "website": "http://banastech.com",
    "license": "",
    "category": "Accounting",
    "sequence": -100,
    "depends": [
        "l10n_in",
        "account",
        "product",
        "base",
        "fleet",
        # "crm_sms",
        # "sms",
        # "banas_branch",
        # "banas_approval_engine",
        "account_payment",
        # 'base_accounting_kit',
        # 'banas_sms_gateway',
    ],

    "data": [
        'data/user_data.xml',
        # 'data/follow_up_cron.xml',
        'data/account_account_data.xml',
        'data/account_journal_data.xml',
        'data/ir_sequence_data.xml',
        'data/relationship_data.xml',
        'data/vehicle_brand_data.xml',
        'data/relationship_data.xml',
        'data/product_data.xml',
        'data/company_data.xml',
        'data/loan_type_data.xml',
        'data/document_type_data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rule_data.xml',
        'views/banas_loan_views.xml',
        'views/payment_views.xml',
        'views/partner_views.xml',
        'views/installment_views.xml',
        # 'views/sms_views.xml',
        'views/document_views.xml',
        'views/res_config_setting.xml',
        'views/account_loan_pay_amount.xml',
        'views/res_company_views.xml',
        'wizard/banas_loan_cal.xml',
        'wizard/banas_loan_report_wizard.xml',
        'wizard/account_loan_post_view.xml',
        'views/menus.xml',
        'report/banas_loan_statement.xml',  
        'report/cibil_report.xml',
        'report/banas_cibil_report_pdf.xml',
        # 'wizard/banas_report_partner_ledger.xml',
    ],
    

    'installable': True,
    'application': True,
    'auto_install': False,
    'external_dependencies': {
         'python': [
             'numpy',
         ],
    },
    'license': 'LGPL-3',
}


